[package]
name = "wadio"
version = "0.1.0"
edition = "2021"

[dependencies]
gumdrop = "0.8.1"
lofty = "0.22.2"
rand = "0.9.0"
tiny_http = "0.12.0"

[dependencies.uuid]
version = "1.15.1"
features = ["v4"]

[dependencies.symphonia]
version = "0.5.4"
features = ["mp3"]
